# Generated by Django 5.0.7 on 2026-03-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asl_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='game_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('sprint', 'Short Word Sprint')], default='standard', max_length=20),
        ),
    ]
